# 학습 초반 실험 07의 validation dice coeff가 빠르게 높아지는 원인을 분석하고자 실험을 계획
# 실험 07에서 cuda OOM으로 인해 bs를 2로 낮추고, resize를 512 -> 1024로 변경하다 보니
# validation dice coeff의 빠른 향상 원인이 무엇인지 알기 어려웠음
# 따라서 bs: 2로 고정 후 원래 resize 값인 512로 재실험

settings:
  # data path
  image_root: "../data/train/DCM"
  label_root: "../data/train/outputs_json"
  tt_image_root: "../data/test/DCM"

  # save path
  saved_dir: "../trained_models"
  submission_dir: "../submissions"

  # seed
  seed: 21

  # classes of hand bone
  classes: [
    'finger-1', 'finger-2', 'finger-3', 'finger-4', 'finger-5',
    'finger-6', 'finger-7', 'finger-8', 'finger-9', 'finger-10',
    'finger-11', 'finger-12', 'finger-13', 'finger-14', 'finger-15',
    'finger-16', 'finger-17', 'finger-18', 'finger-19', 'Trapezium',
    'Trapezoid', 'Capitate', 'Hamate', 'Scaphoid', 'Lunate',
    'Triquetrum', 'Pisiform', 'Radius', 'Ulna']
        
data:
  augs: 'resize_512'
  
train:
  models: 'fcn_resnet101'
  num_epochs: 40
  batch_size: 2
  shuffle: True
  num_workers: 4
  drop_last: False
  lr: 0.0001
  log_interval: 10
  weight_decay: 0.00001

val:
  batch_size: 2
  shuffle: False
  num_workers: 2
  drop_last: False
  val_every: 1

test:
  batch_size: 2
  shuffle: False
  num_workers: 2
  drop_last: False
