settings:
  # data path
  image_root: "../data/train/DCM"
  label_root: "../data/train/outputs_json"
  tt_image_root: "../data/test/DCM"

  # save path
  saved_dir: "../trained_models"
  submission_dir: "../submissions"

  # seed
  seed: 21

  # classes of hand bone
  classes: [
    'finger-1', 'finger-2', 'finger-3', 'finger-4', 'finger-5',
    'finger-6', 'finger-7', 'finger-8', 'finger-9', 'finger-10',
    'finger-11', 'finger-12', 'finger-13', 'finger-14', 'finger-15',
    'finger-16', 'finger-17', 'finger-18', 'finger-19', 'Trapezium',
    'Trapezoid', 'Capitate', 'Hamate', 'Scaphoid', 'Lunate',
    'Triquetrum', 'Pisiform', 'Radius', 'Ulna']

  # library
  lib: "torchvision"
    
train:
  augs: 'resize_512'
  models: 'fcn_resnet50'
  num_epochs: 40
  batch_size: 8
  shuffle: True
  num_workers: 8
  drop_last: True
  lr: 0.0001
  log_interval: 25
  weight_decay: 0.00001

val:
  augs: 'resize_512'
  batch_size: 2
  shuffle: False
  num_workers: 2
  drop_last: False
  val_every: 1

test:
  augs: 'resize_512'
  batch_size: 2
  shuffle: False
  num_workers: 2
  drop_last: False
